"use client";
import {useEffect,useState} from "react";

type Row={id:number;nama:string;username:string;role:"SISWA"|"PEMBIMBING";kelas?:string|null;jurusan?:string|null;sekolah?:string|null;tempat?:{id:number;nama:string}|null;supervisor?:{id:number;nama:string}|null;_count:{journals:number}};
type Place={id:number;nama:string}; type Sup={id:number;nama:string};
export default function UserManager({mode}:{mode:"SISWA"|"PEMBIMBING"}){
 const [rows,setRows]=useState<Row[]>([]),[places,setPlaces]=useState<Place[]>([]),[sups,setSups]=useState<Sup[]>([]),[q,setQ]=useState(""),[editing,setEditing]=useState<Row|null>(null),[open,setOpen]=useState(false),[error,setError]=useState("");
 async function load(){const [a,b,c]=await Promise.all([fetch(`/api/admin/users?role=${mode}&q=${encodeURIComponent(q)}`).then(r=>r.json()),fetch("/api/admin/places").then(r=>r.json()),fetch("/api/admin/users?role=PEMBIMBING").then(r=>r.json())]);setRows(Array.isArray(a)?a:[]);setPlaces(Array.isArray(b)?b:[]);setSups(Array.isArray(c)?c:[])}
 useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t)},[q,mode]);
 async function remove(id:number){if(!confirm("Hapus data ini? Data yang masih memiliki jurnal tidak dapat dihapus."))return;const r=await fetch(`/api/admin/users?id=${id}`,{method:"DELETE"});if(!r.ok){const b=await r.json();setError(b.error||"Gagal menghapus.");return}load()}
 return <><div className="data-toolbar"><input className="data-search" value={q} onChange={e=>setQ(e.target.value)} placeholder={`Cari ${mode.toLowerCase()}...`}/><button className="primary-btn" onClick={()=>{setEditing(null);setOpen(true)}}>Tambah {mode==="SISWA"?"Siswa":"Pembimbing"}</button></div>{error&&<div className="error-box">{error}</div>}<div className="student-table">{rows.map(r=><div className="student-row" key={r.id}><div><b>{r.nama}</b><span>{r.username}{mode==="SISWA"?` · ${r.kelas||"Tanpa kelas"}`:""}</span></div><span>{mode==="SISWA"?(r.tempat?.nama||"Belum ditentukan"):(r.sekolah||"-")}</span><strong>{r._count.journals} jurnal</strong><div className="table-actions"><button className="secondary-btn small-btn" onClick={()=>{setEditing(r);setOpen(true)}}>Edit</button><button className="danger-btn small-btn" onClick={()=>remove(r.id)}>Hapus</button></div></div>)}{!rows.length&&<div className="empty-state"><h3>Belum ada data</h3><p>Belum ada {mode==="SISWA"?"siswa":"pembimbing"} yang sesuai.</p></div>}</div>{open&&<UserModal mode={mode} row={editing} places={places} sups={sups} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}}/>}</>;
}
function UserModal({mode,row,places,sups,onClose,onSaved}:{mode:"SISWA"|"PEMBIMBING";row:Row|null;places:Place[];sups:Sup[];onClose:()=>void;onSaved:()=>void}){
 const [f,setF]=useState<any>({nama:row?.nama||"",username:row?.username||"",password:"",kelas:row?.kelas||"",jurusan:row?.jurusan||"",sekolah:row?.sekolah||"",tempat_pkl_id:row?.tempat?.id||"",pembimbing_id:row?.supervisor?.id||""}),[msg,setMsg]=useState("");
 function set(k:string,v:any){setF((x:any)=>({...x,[k]:v}))}
 async function save(e:React.FormEvent){e.preventDefault();setMsg("");const body={...f,role:mode,tempat_pkl_id:f.tempat_pkl_id?Number(f.tempat_pkl_id):null,pembimbing_id:f.pembimbing_id?Number(f.pembimbing_id):null};if(!body.password)delete body.password;const r=await fetch(row?`/api/admin/users?id=${row.id}`:"/api/admin/users",{method:row?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok){setMsg(b.error||"Gagal menyimpan.");return}onSaved()}
 return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">DATA {mode}</span><h2>{row?"Edit":"Tambah"} {mode==="SISWA"?"Siswa":"Pembimbing"}</h2></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Tutup">×</button></div><div className="modal-grid"><div><label>Nama lengkap</label><input required value={f.nama} onChange={e=>set("nama",e.target.value)}/></div><div><label>Username</label><input required value={f.username} onChange={e=>set("username",e.target.value)}/></div><div><label>Password {row&&<span className="optional">(kosongkan jika tidak diubah)</span>}</label><input type="password" required={!row} value={f.password} onChange={e=>set("password",e.target.value)}/></div><div><label>Sekolah</label><input value={f.sekolah} onChange={e=>set("sekolah",e.target.value)}/></div>{mode==="SISWA"&&<><div><label>Kelas</label><input value={f.kelas} onChange={e=>set("kelas",e.target.value)}/></div><div><label>Jurusan</label><input value={f.jurusan} onChange={e=>set("jurusan",e.target.value)}/></div><div><label>Tempat PKL</label><select value={f.tempat_pkl_id} onChange={e=>set("tempat_pkl_id",e.target.value)}><option value="">Pilih tempat PKL</option>{places.map(p=><option key={p.id} value={p.id}>{p.nama}</option>)}</select></div><div><label>Pembimbing</label><select value={f.pembimbing_id} onChange={e=>set("pembimbing_id",e.target.value)}><option value="">Pilih pembimbing</option>{sups.map(p=><option key={p.id} value={p.id}>{p.nama}</option>)}</select></div></>}</div>{msg&&<div className="error-box">{msg}</div>}<div className="action-row"><button type="button" className="secondary-btn" onClick={onClose}>Batal</button><button className="primary-btn">Simpan</button></div></form></div>
}
